apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-display
spec:
  template:
    # metadata:
    #   annotations:
    #     autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: quay.io/openshift-knative/knative-eventing-sources-event-display
