apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source-broker
spec:
  schedule: "*/1 * * * *"
  data: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: my-broker
