apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: analyzer
  namespace: dev
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: issuesevents
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: analyzer
  reply:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: mailer
