apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: channel-display0
spec:
  template:
    spec:
      containers:
      - image: quay.io/openshift-knative/knative-eventing-sources-event-display
