apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-ch-source
spec:
  schedule: "* * * * *"
  data: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: testchannel